# Font config:
[font]
normal = {  family =  "Hack Nerd Font Mono", style = "Regular" }
size = 16

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

