name: <%= File.basename(Dir.pwd) %>
root: .

windows:
  - editor:
      layout: even-vertical
      panes:
        - nvim
        -
  - agents:
      layout: even-horizontal
      panes:
        - <%= ENV.fetch('AGENT_COMMAND', 'opencode') %>
        - <%= ENV.fetch('AGENT_COMMAND', 'opencode') %>
